SELECT * FROM USERS;

INSERT INTO USERS VALUES(5,'tanay@gmail.com', 0801, 'MENTOR');

UPDATE USERS SET PASSWORD = 1881 WHERE ID = 5;

DELETE FROM USERS WHERE EMAIL = 'test@gmail.com';

desc users;

ALTER TABLE USERS ADD CONSTRAINT unique_email UNIQUE (EMAIL);